package cn.bit101.android.features.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFF9A57)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFEEE3)
val md_theme_light_onPrimaryContainer = Color(0xFF3D1800)

val md_theme_light_secondary = Color(0xFF00ABD6)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC2F3FF)
val md_theme_light_onSecondaryContainer = Color(0xFF00313D)

val md_theme_light_tertiary = Color(0xFFA83159)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E0)
val md_theme_light_onTertiaryContainer = Color(0xFF3F0019)

val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)

val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)

val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E8)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)

val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFC2F2FF)
val md_theme_light_inverseSurface = Color(0xFF00566B)
val md_theme_light_inversePrimary = Color(0xFF5DD4FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006782)
val md_theme_light_outlineVariant = Color(0xFFC0C8CC)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF5DD4FF)
val md_theme_dark_onPrimary = Color(0xFF003545)
val md_theme_dark_primaryContainer = Color(0xFF004D62)
val md_theme_dark_onPrimaryContainer = Color(0xFFBBEAFF)
val md_theme_dark_secondary = Color(0xFFFFBF94)
val md_theme_dark_onSecondary = Color(0xFFE06A1B)
val md_theme_dark_secondaryContainer = Color(0xFFE09665)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFEEE3)
val md_theme_dark_tertiary = Color(0xFFFFB1C2)
val md_theme_dark_onTertiary = Color(0xFF66002C)
val md_theme_dark_tertiaryContainer = Color(0xFF881741)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CC)
val md_theme_dark_outline = Color(0xFF8A9296)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF006782)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF5DD4FF)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF00ABD6)